kind: Secret
apiVersion: v1
type: Opaque
metadata:
  name: pg-cluster-awx-db
  annotations:
    avp.kubernetes.io/remove-missing: "true"
data:
  admin-password: <path:{{ vaultinfra_kv_name }}/data/env/{{ dsc_name }}/apps/awx/values#auth | jsonPath {.adminPassword} | base64encode>

